env:
  browser: true
  commonjs: true
  es2020: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: 'module'
  ecmaFeatures:
    modules: true
plugins:
  - '@typescript-eslint'
rules: {}